# Copyright (C) 2023 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

# This role launches cukinia tests

---
- name: Create temporary test directory
  ansible.builtin.tempfile:
    state: directory
  register: ci_yocto_tmp_test_dir

- name: Launch cukinia tests
  ansible.builtin.shell:
    cmd: >-
      MACHINENAME={{ cukinia_namespace | default(inventory_hostname) }}
      cukinia -f junitxml -o {{ ci_yocto_tmp_test_dir.path }}/cukinia.xml
      /etc/cukinia/cukinia.conf || true
  changed_when: true
- name: Fetch result
  ansible.builtin.fetch:
    src: "{{ ci_yocto_tmp_test_dir.path }}/cukinia.xml"
    dest: >-
      {{ cukinia_test_prefix | default('..') }}/cukinia_{{ inventory_hostname
      }}.xml
    flat: true
