# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
- name: Load distribution-specific variables
  ansible.builtin.include_vars: "{{ seapath_distro }}.yml"
- name: Configure DPDK support
  when: seapath_distro == "Debian"
  block:
    - name: Detect DPDK usage from OVS bridge configuration
      ansible.builtin.set_fact:
        network_configovs_dpdk_enabled: >-
          {{ ovs_bridges | default([])
             | map(attribute='ports', default=[])
             | flatten
             | selectattr('type', 'in', ['dpdk', 'dpdkvhostuserclient'])
             | list | length > 0 }}

    - name: Load vfio-pci module for DPDK
      community.general.modprobe:
        name: vfio-pci
        state: present
        persistent: present
      when: network_configovs_dpdk_enabled | bool

    - name: Switch to OVS with DPDK support
      community.general.alternatives:
        name: ovs-vswitchd
        path: /usr/lib/openvswitch-switch-dpdk/ovs-vswitchd-dpdk
      when: network_configovs_dpdk_enabled | bool

    - name: Switch to OVS without DPDK support
      community.general.alternatives:
        name: ovs-vswitchd
        path: /usr/lib/openvswitch-switch/ovs-vswitchd
      when: not network_configovs_dpdk_enabled | bool

- name: Create OVS configuration # noqa: risky-file-permissions
  ansible.builtin.template:
    src: ovs_configuration.json.j2
    dest: /etc/ovs_configuration.json
    validate: "{{ network_configovs_setup_ovs_command_path }} -v -c -f %s"
  register: network_configovs_ovs_conf
- name: Restart seapath-config_ovs
  ansible.builtin.systemd:
    name: seapath-config_ovs
    state: restarted
  when:
    - network_configovs_apply_config
    - network_configovs_ovs_conf.changed
- name: Register reboot
  ansible.builtin.set_fact:
    need_reboot: true # noqa: var-naming[no-role-prefix]
  when:
    - not network_configovs_apply_config
    - network_configovs_ovs_conf.changed

- name: Run extra ovs-vsctl configuration commands
  ansible.builtin.command: "/usr/bin/ovs-vsctl {{ item }}"
  when:
    - ovs_vsctl_cmds is defined
  loop: "{{ ovs_vsctl_cmds }}"
  changed_when: true
