# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure systemd-resolved DNS settings (no netplan)
  when:
    - dns_servers is defined
    - netplan_configurations is not defined
  block:
    - name: Create /etc/systemd/resolved.conf.d
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Copy SEAPATH systemd-resolved configuration
      ansible.builtin.template:
        src: 30-seapath.conf.j2
        dest: /etc/systemd/resolved.conf.d/30-seapath.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart systemd-resolved

    - name: Create resolv.conf stub link
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: true
      notify: Restart systemd-resolved
    - name: Enable systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        state: started
        enabled: true

- name: Disable resolved if no dns server is defined
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
  when:
    - dns_servers is not defined
    - seapath_distro != "Yocto"
