# Copyright (C) 2022-2024, RTE (http://www.rte-france.com)
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Build the list of Ceph OSD disks
  ansible.builtin.set_fact:
    configure_hardening_physical_machine_ceph_osd_disks: >-
      {{ ceph_osd_disks
         if ceph_osd_disks is defined
         else ([ceph_osd_disk] if ceph_osd_disk is defined else []) }}
- name: Get ceph disk stats
  ansible.builtin.stat:
    path: "{{ item }}"
  loop: "{{ configure_hardening_physical_machine_ceph_osd_disks }}"
  register: configure_hardening_physical_machine_ceph_osd_disk_stat
- name: Restrict ceph sudoers file
  ansible.builtin.template:
    src: sudoers/ceph.j2
    dest: /etc/sudoers.d/ceph-smartctl
    owner: root
    group: root
    mode: "0440"
  when:
    - not revert
    - cluster_ip_addr is defined

- name: Adding ceph user to group privileged
  ansible.builtin.user:
    name: ceph
    groups: privileged
    append: true
  when:
    - not revert
    - cluster_ip_addr is defined

- name: Adding cephadm user to group privileged
  ansible.builtin.user:
    name: cephadm
    groups: privileged
    append: true
  when:
    - not revert
    - cluster_ip_addr is defined
