# Copyright (C) 2022-2024, RTE (http://www.rte-france.com)
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure modules hardening
  ansible.builtin.import_tasks: modules.yml
- name: Configure ceph hardening
  ansible.builtin.import_tasks: ceph.yml
- name: Configure snmp hardening
  ansible.builtin.import_tasks: snmp.yml
- name: Configure services hardening
  ansible.builtin.import_tasks: services.yml
