# Copyright (C) 2022-2024, RTE (http://www.rte-france.com)
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: "Force loading nf_conntrack at boot"
  ansible.builtin.lineinfile:
    dest: /etc/modules-load.d/hardening.conf
    regexp: "^nf_conntrack$"
    line: "nf_conntrack"
    state: present
    mode: "0644"
    create: true
  when: not revert
- name: "Disable force loading nf_conntrack at boot"
  ansible.builtin.lineinfile:
    dest: /etc/modules-load.d/hardening.conf
    regexp: "^nf_conntrack$"
    state: absent
  when: revert
