dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: hv1
    image: docker.io/geerlingguy/docker-debian13-ansible:latest
    privileged: true
  - name: hv2
    image: docker.io/geerlingguy/docker-debian13-ansible:latest
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "${MOLECULE_PROJECT_DIRECTORY}/.."
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    hosts:
      all:
        children:
          hypervisors:
            hosts:
              hv1:
              hv2:
          cluster_machines:
            hosts:
              hv1:
              hv2:

verifier:
  name: ansible
