# Copyright (C) 2023, RTE (http://www.rte-france.com)
# Copyright (C) 2026 Savoir-faire Linux Inc.
# SPDX-License-Identifier: Apache-2.0
#
# This file handle the configuration of ansible-lint

---
exclude_paths:
  - .github
  - roles/deploy_cukinia/files/cukinia

skip_list:
  - role-name # All role names should match "^[a-z_][a-z0-9_]*$"

warn_list:
  - no-handler # "when: result.changed" should trigger a handler instead
  - no-changed-when # Commands should not change things if nothing needs doing

### Why skip these warnings :
#
# - role-name doesn't seem too important to us.
#
# - no-handler and no-changed-when should not be skipped. The
# raised warnings should be corrected as soon as possible for these three rules to
# run on the CI.

extra_vars:
  machine_to_update: node1 # variable used in update playbooks
