# Copyright (C) 2023, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0
#
# This file handle the configuration of ansible-lint

exclude_paths:
  - /etc/ansible/roles    # This is the inside container path for ceph-ansible
  - .github
  - ceph-ansible
  - roles/deploy_cukinia/files/cukinia
  - src/ceph-ansible-site.yaml

# ceph-ansible and cukinia are submodules and seapath don't have control on it.

skip_list:
  - role-name              # All role names should match "^[a-z_][a-z0-9_]*$"

warn_list:
  - no-handler             # "when: result.changed" should trigger a handler instead
  - no-changed-when        # Commands should not change things if nothing needs doing
  - no-relative-paths      # Doesn't need a relative path in role

### Why skip these warnings :
#
# - role-name doesn't seem too important to us.
#
# - no-handler, no-changed-when and no-relative-paths should not be skipped. The
# raised warnings should be corrected as soon as possible for these three rules to
# run on the CI.

extra_vars:
  machine_to_update: node1 # variable used in update playbooks
