// Copyright (C) 2020, RTE (http://www.rte-france.com)
// SPDX-License-Identifier: CC-BY-4.0

Setup machines with Ansible
===========================
:toc:
:sectnumlevels: 1

== Introduction

The distribution images generated by Yocto are preconfigured as much as possible
but some elements cannot be statically configured during image creation or are
specific settings that cannot be included in a generic image.

This is the case for example for the network settings, the hostname or the
high-availability cluster setup.

To perform these tasks we use Ansible which is a tool designed to configure
Linux machines.

Ansible allows you to play actions contained in Ansible playbooks to Linux
machines described with their settings in an Ansible Inventory.

The Ansible documentation is accessible at https://docs.ansible.com/.

== Prerequisites

Machines that need to be configured by Ansible simply need to provide SSH access
and have a Unix Shell and a Python interpreter. The Votp images already fit with
this requirements.

The client machine that is going to run Ansible needs the Ansible application,
an Inventory file and playbook files to play. To install Ansible in this machine
please refer to the Ansible documentation at
https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html.

*Note:* Only the Ansible version 2.9 was tested. We strongly recommand to use
and install this version.

You also need to install Ansible plugin requirements defined in
_ansible-requirements.yaml_. To do this once you have installed the ansible
client enter the following command at the top of the ansible git repository:

 $ ansible-galaxy install -r ansible-requirements.yaml

== Inventory

Ansible plays playbooks in hosts described in an Ansible inventory.
In this inventory are described the hosts, the way to access these hosts,
their configurations. Hosts can be grouped into groups.
Ansible Inventory documentation is available at
https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html.

In the same directory as this file you can find the file inventory_example.yaml
which is an example file of inventory Ansible to work with HA cluster composed
of 2 hypervisors, an observer and a virtual machine. This file is in YAML format.
Other format are valid for inventory file but in this document we will only
cover the YAML format.

*Note:* If you are not familiar with the YAML format you will find a description
here: https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

You need to pass your inventory file to all Ansible command with the _-i_
argument. To validate your Ansible inventory file you can use the
_ansible-inventory_ command with _--list_ argument.
For instance if your Ansible file is cluster.yaml:

 $ ansible-inventory -i cluster.yaml --list

An Ansible iventory file respects a hierarchy. Ansible action can be later
applied to all hosts included in this level. All level can have _hosts_ and
_vars_ (variables).
The top level is _all_. _hosts_ defined here are ungrouped and _vars_ are
globals.
If you defined a _children_ entry in _all_ you can define group.
For instance:

[source,yaml]
----
all:
    hosts:
        host1:
    vars:
        my_global_var: variable_content
    chlidren:
        group1:
            hosts:
                host2:
                host3:
            vars:
                my_group1_scope_variable: variable_content
        group2:
            hosts:
                host4:
                    my_host_variable: variable_content
----

Once you have an Ansible inventory you can test host connexion with the ping
module:

 $ ansible -i cluster.yaml all -m ping

Like all Ansible commands you need to specify your inventory file with the _-i_
argument, the host or group to apply the action.
For instance here we use the module ping with the _-m ping_ argument.

To check all host in _group1_:

 $ ansible -i cluster.yaml group1 -m ping

To check only _host3_:

 $ ansible -i cluster.yaml host3 -m ping

