[tox]
env_list =
    molecule-roles
    molecule-playbooks

labels =
    molecule = molecule-roles, molecule-playbooks

[testenv:molecule-roles]
description = Run Molecule tests for all roles that have molecule/<scenario>/
deps =
    -r molecule_requirements.txt
allowlist_externals =
    bash
commands =
    bash scripts/run-molecule-roles.sh

[testenv:molecule-playbooks]
description = Run Molecule tests for all playbooks
deps =
    -r molecule_requirements.txt
commands =
    molecule test --all
changedir = playbooks
