[tox]
envlist = molecule
skipsdist = true

[testenv:molecule]
description = Run Molecule tests for all roles that have molecule/<scenario>/
deps =
    -r molecule_requirements.txt
allowlist_externals =
    bash
commands =
    bash scripts/run-molecule-roles.sh
