# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Create a symbolic link for qemu-kvm/x86-64
  ansible.builtin.file:
    src: /usr/libexec/qemu-kvm
    dest: /usr/bin/qemu-system-x86_64
    state: link
