# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Enable and start virtsecretd.socket
  ansible.builtin.systemd:
    name: virtsecretd.socket
    state: started
    enabled: true
- name: Enable and start virtqemud.socket
  ansible.builtin.systemd:
    name: virtqemud.socket
    state: started
    enabled: true
- name: Enable and start virtstoraged.socket
  ansible.builtin.systemd:
    name: virtstoraged.socket
    state: started
    enabled: true
