# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Apply vim configurations
  ansible.builtin.import_tasks: vim.yml
- name: Remove old admin user
  ansible.builtin.import_tasks: remove_old_admin.yml
- name: Apply logging configurations
  ansible.builtin.import_tasks: logging.yml
- name: Apply users configurations
  ansible.builtin.import_tasks: users.yml
- name: Apply sysctl configurations
  ansible.builtin.import_tasks: sysctl.yml
- name: Apply apt configurations
  ansible.builtin.import_tasks: apt.yml
- name: Apply GRUB configurations
  ansible.builtin.import_tasks: grub.yml
- name: Apply ssh configurations
  ansible.builtin.import_tasks: ssh.yml
