---
- name: Prepare test environment (Debian 13)
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Install syslog-ng
      ansible.builtin.apt:
        name:
          - syslog-ng
        state: present
        update_cache: true
