# Copyright (C) 2026 RTE
# SPDX-License-Identifier: Apache-2.0
---
deploy_prometheus_exporters_supported_exporters:
  - node-exporter
  - podman-exporter
  - libvirt-exporter
  - insatomcat-exporter
  - ha_cluster_exporter

deploy_prometheus_exporters_default_images:
  node-exporter: quay.io/prometheus/node-exporter:latest
  podman-exporter: quay.io/navidys/prometheus-podman-exporter
  libvirt-exporter: ghcr.io/inovex/prometheus-libvirt-exporter:2.3.1
  insatomcat-exporter: docker.io/insatomcat/insatomcat-exporter:latest
  ha_cluster_exporter: docker.io/insatomcat/ha-cluster-exporter:0.0.1

deploy_prometheus_exporters_group_exporters:
  cluster_machines:
    - ha_cluster_exporter
  hypervisors:
    - podman-exporter
    - libvirt-exporter
    - insatomcat-exporter
