# Copyright (C) 2022-2024, RTE (http://www.rte-france.com)
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: "Configure login.defs"
  ansible.builtin.lineinfile:
    dest: "{{ configure_hardening_login_defs_file }}"
    regexp: "^{{ item }}$"
    line: "{{ item }}"
    state: present
    create: true
    mode: "0644"
  with_items:
    - PASS_MAX_DAYS 90
  when: not revert
- name: "Unconfigure login.defs"
  ansible.builtin.lineinfile:
    dest: "{{ configure_hardening_login_defs_file }}"
    regexp: "^{{ item }}$"
    state: absent
  with_items:
    - PASS_MAX_DAYS 90
  when: revert
