# Copyright (C) 2022-2024, RTE (http://www.rte-france.com)
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Create groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  when: not revert
  with_items:
    - ansible
    - privileged

- name: Configure kernel parameters hardening
  ansible.builtin.import_tasks: kernel.yml
- name: Configure sysctl hardening
  ansible.builtin.import_tasks: sysctl.yml
- name: Configure services hardening
  ansible.builtin.import_tasks: services.yml
- name: Configure profile hardening
  ansible.builtin.import_tasks: profile.yml
- name: Configure ssh hardening
  ansible.builtin.import_tasks: ssh.yml
- name: Configure sudo hardening
  ansible.builtin.import_tasks: sudoers.yml
- name: Configure cockpit hardening
  ansible.builtin.import_tasks: cockpit.yml
- name: Configure login hardening
  ansible.builtin.import_tasks: login.yml
- name: Configure su hardening
  ansible.builtin.import_tasks: su.yml
- name: Configure securetty hardening
  ansible.builtin.import_tasks: securetty.yml
- name: Configure GRUB hardening
  ansible.builtin.import_tasks: grub.yml
- name: Configure syslog hardening
  ansible.builtin.import_tasks: syslog.yml
- name: Configure audit hardening
  ansible.builtin.import_tasks: audit.yml
