# Copyright (C) 2022-2024, RTE (http://www.rte-france.com)
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Create securetty
  ansible.builtin.copy:
    content: ""
    dest: /etc/securetty
    force: false
    group: "{{ configure_hardening_etc_securetty_group }}"
    owner: root
    mode: "0644"
  when: not revert
- name: Remove securetty
  ansible.builtin.file:
    path: /etc/securetty
    state: absent
  when: revert

- name: Enable securetty in pam login
  ansible.builtin.lineinfile:
    dest: /etc/pam.d/login
    insertafter: "auth       optional   pam_faildelay.so  delay=3000000"
    line: "auth   [success=ok ignore=ignore user_unknown=ignore default=die]    pam_securetty.so"
  when: not revert
- name: Disable securetty in pam login
  ansible.builtin.lineinfile:
    dest: /etc/pam.d/login
    regexp: "^auth    \\[success=ok ignore=ignore user_unknown=ignore default=die\\]    pam_securetty.so"
    state: absent
  when: revert
