# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Set auditd enriched log format
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: '^log_format\s*='
    line: 'log_format = ENRICHED'
