# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Remove quiet from GRUB_CMDLINE_LINUX_DEFAULT option in grub conf
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\")(.*?[ ])?quiet([ ].*)?(\")$"
    line: "\\1\\2\\3\\4"
    backrefs: true
  notify: Update-grub

- name: Make sure GRUB_CMDLINE_LINUX_DEFAULT has no double space
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)[ ][ ](.*\")"
    line: "\\1 \\2"
    state: present
    backrefs: true
  register: configure_seapath_distro_doublespace
  until: not configure_seapath_distro_doublespace.changed
  delay: 1
  retries: 10

- name: Make sure GRUB_CMDLINE_LINUX exists 1/2
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX=\".*\""
    state: absent
  check_mode: true
  changed_when: false
  register: configure_seapath_distro_check_grub_cmdline_linux

- name: Make sure GRUB_CMDLINE_LINUX exists 2/2
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    state: present
    line: "GRUB_CMDLINE_LINUX=\" \""
  when: configure_seapath_distro_check_grub_cmdline_linux.found == 0

- name: Make sure GRUB_CMDLINE_LINUX starts with a space
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX=)\"([ ]*)(.*)\""
    line: '\1" \3"'
    state: present
    backrefs: true

- name: Make grub conf
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX=(?!.* {{ item }})\"[^\"]*)(\".*)"
    line: "\\1 {{ item }}\\2"
    state: present
    backrefs: true
  notify: Update-grub
  with_items:
    - ipv6.disable=1
    - efi=runtime
    - fsck.mode=force
    - fsck.repair=yes
    - "{{ grub_append | default([]) }}"

- name: Grub conf osprober
  ansible.builtin.lineinfile:
    dest: /etc/default/grub
    regexp: "^#?GRUB_DISABLE_OS_PROBER=.*$"
    line: "GRUB_DISABLE_OS_PROBER=true"
    state: present
  notify: Update-grub
