# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Remove old admin user
  when: seapath_distro in ["Debian", "OracleLinux"]
  ansible.builtin.import_tasks: remove_old_admin.yml

- name: Apply vim configurations
  ansible.builtin.import_tasks: vim.yml
- name: Apply logging configurations
  ansible.builtin.import_tasks: logging.yml
- name: Apply users configurations
  ansible.builtin.import_tasks: users.yml
- name: Apply sysctl configurations
  ansible.builtin.import_tasks: sysctl.yml
- name: Apply GRUB configurations
  ansible.builtin.import_tasks: grub.yml

- name: SEAPATH Debian specific distro configuration
  when: seapath_distro == "Debian"
  block:
    - name: Apply Debian apt configurations
      ansible.builtin.include_tasks: debian/apt.yml
    - name: Apply Debian ssh configurations
      ansible.builtin.include_tasks: debian/ssh.yml
    - name: Apply Debian GRUB configurations
      ansible.builtin.include_tasks: debian/grub.yml

- name: SEAPATH OracleLinux specific distro configuration
  when: seapath_distro == "OracleLinux"
  block:
    - name: Format GRUB_CMDLINE_LINUX_DEFAULT option
      ansible.builtin.include_tasks: debian/grub_cmdline_default_linux.yml
    - name: Apply OracleLinux network configurations
      ansible.builtin.include_tasks: oraclelinux/network.yml
