# Copyright (C) 2025 RTE
# Copyright (C) 2024 Red Hat, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Restart sysfsutils
  ansible.builtin.systemd:
    name: sysfsutils.service
    state: restarted

- name: Start new slices
  ansible.builtin.systemd:
    name: "{{ item }}.slice"
    state: started
    daemon_reload: true
  with_items:
    - "machine-rt"
    - "machine-nort"
    - "ovs"

- name: Start new slices REVERT
  ansible.builtin.systemd:
    name: "{{ item }}.slice"
    state: stopped
    daemon_reload: true
  with_items:
    - "machine-rt"
    - "machine-nort"
    - "ovs"
