# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-debian13-ansible:latest
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "${MOLECULE_PROJECT_DIRECTORY}/.."
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible

...