# Copyright (C) 2026 RTE
# SPDX-License-Identifier: Apache-2.0

---
- name: Populate service facts
  ansible.builtin.service_facts:
- name: Stop and mask irqbalance.service if it is installed
  ansible.builtin.systemd:
    name: irqbalance.service
    state: stopped
    enabled: false
    masked: true
  when:
    - "'irqbalance.service' in services"
    - "services['irqbalance.service'].status != 'not-found'"
