# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Apply modules configurations
  ansible.builtin.import_tasks: modules.yml
- name: Apply sriov configurations
  ansible.builtin.import_tasks: sriov.yml
- name: Apply watchdog configurations
  ansible.builtin.import_tasks: watchdog.yml
- name: Apply systemd slices configurations
  ansible.builtin.import_tasks: slices.yml
- name: Apply tuned configurations
  ansible.builtin.import_tasks: tuned.yml
- name: Apply libvirt configurations
  ansible.builtin.import_tasks: libvirt.yml
