# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Add vhost_vsock to /etc/modules-load.d
  ansible.builtin.copy:
    content: |
      vhost_vsock
    dest: /etc/modules-load.d/vhost_vsock.conf
    owner: root
    group: root
    mode: "0644"
