# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Create tuned seapath-rt profile folder
  ansible.builtin.file:
    path: "{{ configure_hypervisor_tuned_profiles_dir }}/seapath-rt-host"
    state: directory
    mode: "0755"

- name: Tuned path
  ansible.builtin.set_fact:
    configure_hypervisor_tuned_path: "{{ custom_tuned_profile_path if custom_tuned_profile_path is defined else 'tuned.conf.j2' }}"

- name: Copy seapath-rt-host tuned profile conf
  ansible.builtin.template:
    src: "{{ configure_hypervisor_tuned_path }}"
    dest: "{{ configure_hypervisor_tuned_profiles_dir }}/seapath-rt-host/tuned.conf"
    group: root
    owner: root
    mode: "0644"
  register: configure_hypervisor_tuned_conf

- name: Copy seapath-rt-host tuned profile script
  ansible.builtin.copy:
    src: tuned-script.sh
    dest: "{{ configure_hypervisor_tuned_profiles_dir }}/seapath-rt-host/script.sh"
    owner: root
    group: root
    mode: "0755"
  register: configure_hypervisor_tuned_script

- name: Remove tuned dynamic tuning
  ansible.builtin.lineinfile:
    path: /etc/tuned/tuned-main.conf
    state: present
    regexp: "^#?dynamic_tuning = .*$"
    line: "dynamic_tuning = 0"
  register: configure_hypervisor_tuned_main_conf

- name: Set seapath-rt-host as active tuned profile
  ansible.builtin.copy:
    content: "seapath-rt-host\n"
    dest: /etc/tuned/active_profile
    owner: root
    group: root
    mode: "0644"
  register: configure_hypervisor_tuned_profile_set
  when: isolcpus is defined

- name: Enable tuned.service
  ansible.builtin.systemd:
    name: tuned.service
    enabled: true
    state: started

- name: Restart tuned to apply profile without rollback
  ansible.builtin.systemd:
    name: tuned.service
    state: restarted
  when: >
    configure_hypervisor_tuned_main_conf.changed or
    (isolcpus is defined and
     (configure_hypervisor_tuned_conf.changed or
      configure_hypervisor_tuned_script.changed or
      configure_hypervisor_tuned_profile_set.changed))

- name: Unload tuned profile
  ansible.builtin.command: tuned-adm off
  when: isolcpus is not defined
  changed_when: true
