# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Create /etc/systemd/system.conf.d
  ansible.builtin.file:
    path: /etc/systemd/system.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Systemd conf Watchdog
  ansible.builtin.copy:
    src: 30-watchdog.conf
    dest: /etc/systemd/system.conf.d/30-watchdog.conf
    owner: root
    group: root
    mode: "0644"
