---
# handlers for ansible-role-systemd-networkd

- name: Restart udev
  ansible.builtin.service:
    name: "{{ network_systemdnetworkd_service_name_udev }}"
    state: restarted

- name: Reload systemd-networkd
  ansible.builtin.service:
    name: systemd-networkd
    state: reloaded
  when: network_systemdnetworkd_apply_config

- name: Check reboot
  ansible.builtin.set_fact:
    need_reboot: true # noqa: var-naming[no-role-prefix]
  when: not network_systemdnetworkd_apply_config
