# Copyright (C) 2026 RTE
# SPDX-License-Identifier: Apache-2.0
---
galaxy_info:
  author: "Seapath"
  namespace: "seapath"
  description: Create local partitions, optionally under LVM, and mount them by UUID.
  min_ansible_version: "2.16"
  license: Apache-2.0
  platforms:
    - name: Debian
      versions:
        - all
dependencies: []
