# Copyright (C) 2024 RTE
# Copyright (C) 2024 Red Hat, Inc.
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Create system alternative for a debian kvm path
  community.general.alternatives:
    name: "debian kvm"
    path: "/usr/libexec/qemu-kvm"
    link: "/usr/bin/qemu-system-x86_64"
