# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Format GRUB_CMDLINE_LINUX_DEFAULT option
  ansible.builtin.import_tasks: debian/grub_cmdline_default_linux.yml

- name: Remove /etc/default/grub.d/*.cfg (FAI)
  ansible.builtin.file:
    path: "/etc/default/grub.d/{{ item }}"
    state: absent
  with_items:
    - 20_efi_ipv6.cfg
    - 30_console.cfg
