# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Disable PerSourcePenalties
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PerSourcePenalties.*$"
    line: "PerSourcePenalties no"
    state: present
  notify: Restart sshd
  when: ansible_distribution_release == 'trixie'
