---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: node
    image: docker.io/geerlingguy/docker-debian13-ansible:latest
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "${MOLECULE_PROJECT_DIRECTORY}/.."
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        cluster_containers:
          web:
            images:
              - name: localhost/molecule-web:1
                archive: /tmp/molecule-web-1.tar
            quadlets:
              - "${MOLECULE_SCENARIO_DIRECTORY}/files/web.container.j2"
              - "${MOLECULE_SCENARIO_DIRECTORY}/files/web.network"
            config:
              - "${MOLECULE_SCENARIO_DIRECTORY}/files/web.conf.j2"
              - "${MOLECULE_SCENARIO_DIRECTORY}/files/web.cid"
            rbd:
              size: 64M
            ip: 192.0.2.10

verifier:
  name: ansible
