# Copyright (C) 2024 Savoir-faire Linux, Inc
# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
- name: Verify roles variable are defined
  ansible.builtin.import_tasks: validate.yml

- name: Copy NIC irq affinity script
  ansible.builtin.copy:
    src: setup_nic_irq_affinity.py
    dest: /etc/systemd/system/setup_nic_irq_affinity.py
    mode: "0755"
  notify: Enable and start NIC irq affinity service

- name: Copy NIC irq affinity service
  ansible.builtin.copy:
    src: setup_nic_irq_affinity.service
    dest: /etc/systemd/system/setup_nic_irq_affinity.service
    mode: "0644"
  notify: Enable and start NIC irq affinity service

- name: Copy NIC irq affinity environment file
  ansible.builtin.template:
    src: setup_nic_irq_affinity.j2
    dest: /etc/default/setup_nic_irq_affinity
    mode: "0644"
  notify: Enable and start NIC irq affinity service
