# Copyright (C) 2024 Savoir-faire Linux, Inc
# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
- name: Verify roles variable are defined
  ansible.builtin.import_tasks: validate.yml

- name: Disable legacy NIC IRQ affinity services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
    daemon_reload: true
  failed_when: false
  loop:
    - setup_nic_irq_affinity.service

- name: Remove legacy NIC IRQ affinity files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/systemd/system/setup_nic_irq_affinity.py
    - /etc/systemd/system/setup_nic_irq_affinity.service
    - /etc/default/setup_nic_irq_affinity

- name: Deploy IRQ affinity script
  ansible.builtin.copy:
    src: set_nic_irq_affinity.sh
    dest: /usr/local/bin/set_nic_irq_affinity.sh
    mode: "0755"
  notify: Restart NIC IRQ affinity service

- name: Deploy IRQ affinity monitor daemon
  ansible.builtin.copy:
    src: nic-irq-monitor.sh
    dest: /usr/local/bin/nic-irq-monitor.sh
    mode: "0755"
  notify: Restart NIC IRQ affinity service

- name: Deploy IRQ affinity config
  ansible.builtin.template:
    src: nic-irq-affinity.conf.j2
    dest: /etc/nic-irq-affinity.conf
    mode: "0644"
  notify: Restart NIC IRQ affinity service

- name: Deploy IRQ affinity service
  ansible.builtin.copy:
    src: nic-irq-affinity.service
    dest: /etc/systemd/system/nic-irq-affinity.service
    mode: "0644"
  notify: Restart NIC IRQ affinity service

- name: Enable NIC IRQ affinity service
  ansible.builtin.systemd:
    name: nic-irq-affinity.service
    enabled: true
    daemon_reload: true
