# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure netplan if needed
  when: netplan_configurations is defined
  block:
    - name: Create /etc/netplan directory
      ansible.builtin.file:
        path: /etc/netplan
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Copy Netplan configuration file
      ansible.builtin.template:
        src: "../{{ item }}"
        dest: "/etc/netplan/{{ item | basename | replace('.j2', '') }}"
        owner: root
        group: root
        mode: "0600"
      with_items: "{{ netplan_configurations }}"
      notify: Apply Netplan configuration
    - name: Check of netplan-configure service exist on the target
      ansible.builtin.service_facts:
    - name: Enable netplan-configure.service
      ansible.builtin.systemd:
        name: netplan-configure.service
        enabled: true
        state: restarted
      when:
        - '"netplan-configure.service" in ansible_facts.services'
    - name: Avoid reboot for netplan
      ansible.builtin.set_fact:
        need_reboot: false # noqa: var-naming[no-role-prefix]
