# Copyright (C) 2020, RTE (http://www.rte-france.com)
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

cukinia_log "$(_colorize yellow "--- running tests on real time ---")"
# check that kernel is PREEMPT RT
test_id "SEAPATH-00075" as "kernel is PREEMPT RT" cukinia_cmd grep "PREEMPT_RT" /proc/version

if [ -f /sys/kernel/realtime ]; then
    SYS_KERNEL_REALTIME_CONTENT="$(cat /sys/kernel/realtime)"
else
    SYS_KERNEL_REALTIME_CONTENT=0
fi

when "[ -f /sys/kernel/realtime ]" test_id "SEAPATH-00076" as "kernel is using the RT patch" cukinia_test $SYS_KERNEL_REALTIME_CONTENT -eq 1
