# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Lineinfile in hosts file for logstash-seapath
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: ".* logstash-seapath$"
    line: "{{ logstash_server_ip }} logstash-seapath"
    state: present
  when: logstash_server_ip is defined
