# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: "Add initramfs-tools scripts: script file (LVM rebooter and log handling)"
  ansible.builtin.copy:
    src: initramfs-tools/scripts/
    dest: /etc/initramfs-tools/scripts/
    mode: "0755"
  notify: Rebuild initramfs if necessary

- name: Get the /var/log/ device
  ansible.builtin.command: "findmnt -n -o SOURCE --target /var/log"
  register: configure_physical_machine_varlog_dev
  changed_when: false

- name: Set fact /var/log/ device
  ansible.builtin.set_fact:
    configure_physical_machine_lvm_rebooter_log_device: "{{ configure_physical_machine_varlog_dev.stdout }}"

- name: Get the /var/log/ relative path
  ansible.builtin.shell: "realpath --relative-to=$(findmnt -n -o TARGET --target /var/log/) /var/log"
  register: configure_physical_machine_varlog_path
  changed_when: false

- name: Set fact /var/log/ relative path
  ansible.builtin.set_fact:
    configure_physical_machine_lvm_rebooter_log_path: "{{ configure_physical_machine_varlog_path.stdout }}"

- name: Apply initramfs-tools configurations
  when: configure_physical_machine_initramfs == "initramfs-tools"
  ansible.builtin.include_tasks: initramfs/initramfs-tools.yml
- name: Apply dracut configurations
  when: configure_physical_machine_initramfs == "dracut"
  ansible.builtin.include_tasks: initramfs/dracut.yml
