# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Temp fix for synchronize to force evaluate variables
  ansible.builtin.set_fact:
    ansible_host: "{{ ansible_host }}"

- name: Apply sysctl configurations
  ansible.builtin.import_tasks: sysctl.yml
- name: Install SEAPATH python modules
  ansible.builtin.import_tasks: python.yml
- name: Apply chrony configurations
  ansible.builtin.import_tasks: chrony.yml
- name: Apply modules configurations
  ansible.builtin.import_tasks: modules.yml
- name: Apply hosts configurations
  ansible.builtin.import_tasks: hosts.yml
- name: Apply libvirt configurations
  ansible.builtin.import_tasks: libvirt.yml
- name: Apply initramfs configurations
  when: configure_physical_machine_initramfs is defined
  ansible.builtin.include_tasks: initramfs.yml
- name: Apply LVM configurations
  ansible.builtin.import_tasks: lvm.yml
- name: Apply OpenVSwitch configurations
  when: services['ovs-vswitchd.service'] is defined
  ansible.builtin.include_tasks: openvswitch.yml
- name: Apply network configurations
  ansible.builtin.import_tasks: network.yml
- name: Configure pacemaker
  when: services['pacemaker.service'] is defined
  ansible.builtin.include_tasks: pacemaker.yml

- name: SEAPATH Debian specific physical machine configuration
  when: seapath_distro == "Debian"
  block:
    - name: Apply Debian lvm configurations
      ansible.builtin.include_tasks: debian/lvm.yml
    - name: Configure Debian SEAPATH pacemaker ressource agents
      when: "'cluster_machines' in group_names"
      ansible.builtin.include_tasks: debian/ressource-agents.yml

- name: SEAPATH CentOS specific physical machine configuration
  when: seapath_distro == "CentOS"
  block:
    - name: Apply CentOS libvirt configurations
      ansible.builtin.include_tasks: centos/libvirt.yml
    - name: Apply CentOS firewalld configurations
      ansible.builtin.include_tasks: centos/firewalld.yml
    - name: Configure CentOS SEAPATH pacemaker ressource agents
      when: "'cluster_machines' in group_names"
      ansible.builtin.include_tasks: centos/ressource-agents.yml
