# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Add extra modules to load on boot
  ansible.builtin.template:
    src: extra_modules.conf.j2
    dest: /etc/modules-load.d/extra_modules.conf
    owner: root
    group: root
    mode: "0644"
