# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Create pacemaker.service.d directory
  ansible.builtin.file:
    path: /etc/systemd/system/pacemaker.service.d/
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Copy pacemaker.service drop-in
  ansible.builtin.template:
    src: pacemaker_override.conf.j2
    dest: /etc/systemd/system/pacemaker.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  notify: Trigger daemon-reload
  register: configure_physical_machine_pacemaker_corosync
- name: Get Pacemaker service Status
  ansible.builtin.systemd:
    name: "pacemaker.service"
  register: configure_physical_machine_pacemaker_service_status
- name: Disable pacemaker (reinstall step 1/2)
  ansible.builtin.systemd:
    name: pacemaker.service
    enabled: false
  when: configure_physical_machine_pacemaker_corosync.changed and configure_physical_machine_pacemaker_service_status.status.UnitFileState == "enabled"
- name: Enable pacemaker (reinstall step 2/2)
  ansible.builtin.systemd:
    name: pacemaker.service
    enabled: true
  when: configure_physical_machine_pacemaker_corosync.changed and configure_physical_machine_pacemaker_service_status.status.UnitFileState == "enabled"
