# Copyright (C) 2024 Red Hat, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Daemon-reload
  ansible.builtin.service:
    daemon_reload: true

- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Update Grub
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  changed_when: true
