# Copyright (C) 2025, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

# This playbook configures and sets up Ceph with cephadm.

---
- name: Install cephadm prerequisites
  hosts: cluster_machines
  become: true
  gather_facts: true
  tasks:
    - name: Detect SEAPATH distribution
      ansible.builtin.include_role:
        name: detect_seapath_distro
    - name: Load cephadm_install distribution-specific variables
      ansible.builtin.include_vars: "../vars/{{ seapath_distro }}_cephadm_install.yml"
    - name: Install cephadm prerequisites
      ansible.builtin.include_role:
        name: cephadm_install

- name: Prepare Ceph installation
  hosts: osds
  become: true
  gather_facts: true
  roles:
    - detect_seapath_distro
    - ceph_prepare_installation

- name: Cephadm
  hosts: cluster_machines
  become: true
  roles:
    - detect_seapath_distro
    - cephadm
    - role: deploy_cephfs
      when: deploy_cephfs is defined and deploy_cephfs | bool
