# Copyright (C) 2023, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

---
- name: Detect Seapath distribution
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  roles:
    - detect_seapath_distro
- name: Prerequis machine debian
  gather_facts: true
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  become: true
  roles:
    - syslog_ng_client
    - debian
- name: Prerequis physical machine debian
  hosts:
    - cluster_machines
    - standalone_machine
  become: true
  roles:
    - debian_physical_machine
- name: Backup_restore on cluster machines
  hosts:
    - cluster_machines
  become: true
  roles:
    - backup_restore
- name: Prerequis hypervisor debian
  hosts:
    - hypervisors
    - standalone_machine
  become: true
  roles:
    - debian_hypervisor

- name: Add admin user to haclient group
  hosts:
    - cluster_machines
  become: true
  tasks:
    - name: Add admin user to haclient group
      ansible.builtin.user:
        name: "{{ admin_user }}"
        groups: haclient
        append: true

- name: Disable libvirt-guests.service
  hosts:
    - cluster_machines
  become: true
  tasks:
    - name: Disable libvirt-guests.service
      ansible.builtin.systemd:
        name: libvirt-guests.service
        enabled: false
        state: stopped

- name: Upload extra files
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  become: true
  roles:
    - upload_extra_files

- name: Remove what is not needed after installation on guests
  hosts:
    - VMs
  become: true
  tasks:
    - name: Uninstall apt packages not required after installation (trixie)
      ansible.builtin.apt:
        name:
          - gcc-12-base
          - libargon2-1
          - libfdisk1
          - libunistring2
        state: absent
        purge: true
        autoremove: true
      when: ansible_distribution_release == 'trixie'

- name: Remove what is not needed after installation
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  become: true
  tasks:
    - name: Create /etc/apt/sources.list.d/ # noqa: risky-file-permissions
      ansible.builtin.file:
        state: directory
        path: /etc/apt/sources.list.d/
    - name: Uninstall ceph packages
      ansible.builtin.apt:
        name:
          - ceph
          - ceph-base
          - ceph-mgr
          - ceph-mon
          - ceph-osd
          - ceph-volume
        state: absent
        purge: true
        autoremove: true
      when: force_cephadm | default(false)
    - name: Uninstall apt packages not required after installation (all debian version)
      ansible.builtin.apt:
        name:
          - fdisk
          - ifupdown
        state: absent
        purge: true
        autoremove: true
    - name: Uninstall apt packages not required after installation (trixie)
      ansible.builtin.apt:
        name:
          - dhcpcd-base
          - libapt-pkg6.0
          - usr-is-merged
        state: absent
        purge: true
        autoremove: true
      when: ansible_distribution_release == 'trixie'
    - name: Disable unused systemd services
      ansible.builtin.systemd:
        unit: "{{ item }}"
        state: stopped
        enabled: false
        no_block: true
      with_items:
        - apt-daily-upgrade.timer
        - apt-daily.timer
