---
# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

- name: Prerequis machine oraclelinux
  gather_facts: true
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  become: true
  roles:
    - syslog_ng_client
    - oraclelinux
- name: Prerequis physical machine oraclelinux
  hosts:
    - cluster_machines
    - standalone_machine
  become: true
  roles:
    - oraclelinux_physical_machine
- name: Prerequis physical machine oraclelinux
  hosts:
    - cluster_machines
  become: true
  roles:
    - backup_restore

- name: Add admin user to haclient group
  hosts:
    - cluster_machines
  become: true
  tasks:
    - name: Add admin user to haclient group
      ansible.builtin.user:
        name: "{{ admin_user }}"
        groups: haclient
        append: true

- name: Disable libvirt-guests.service
  hosts:
    - cluster_machines
  become: true
  tasks:
    - name: Disable libvirt-guests.service
      ansible.builtin.systemd:
        name: libvirt-guests.service
        enabled: false
        state: stopped

- name: Upload extra files
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  become: true
  roles:
    - upload_extra_files
