---
# Copyright (C) 2025 RTE
# SPDX-License-Identifier: Apache-2.0

- name: OracleLinux machine prerequisites
  gather_facts: true
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  become: true
  roles:
    - syslog_ng_client
    - role: configure_seapath_distro
      vars:
        configure_seapath_distro_vim_config_dir: /etc
        configure_seapath_distro_grub_update_command: grub2-mkconfig -o /boot/grub2/grub.cfg
- name: OracleLinux physical machine prerequisites
  hosts:
    - cluster_machines
    - standalone_machine
  become: true
  roles:
    - role: configure_physical_machine
      vars:
        configure_physical_machine_distro_extra_modules:
          - br_netfilter
- name: Backup_restore on cluster machines
  hosts:
    - cluster_machines
  become: true
  roles:
    - backup_restore

- name: Add admin user to haclient group
  hosts:
    - cluster_machines
  become: true
  tasks:
    - name: Add admin user to haclient group
      ansible.builtin.user:
        name: "{{ admin_user }}"
        groups: haclient
        append: true

- name: Disable libvirt-guests.service
  hosts:
    - cluster_machines
  become: true
  tasks:
    - name: Disable libvirt-guests.service
      ansible.builtin.systemd:
        name: libvirt-guests.service
        enabled: false
        state: stopped

- name: Upload extra files
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  become: true
  roles:
    - upload_extra_files
