on:
  workflow_call:
    inputs:
      seapath-flavor:
        type: string
        required: true
        description: Flavor of SEAPATH that is being tested (e.g. Debian, Yocto)
      runner-label:
        type: string
        required: true
        description: Label of the runner used to deploy and test machines.
      inventories-repository:
        type: string
        required: true
        description: URL to clone the repository containing the private inventories.
      inventories-repository-branch:
        type: string
        required: false
        default: "main"
        description: Branch to clone of the repository containing the private inventories.
      hyp-inventories:
        type: string
        required: true
        description: --inventory flags for the hypervisor.
      hyp-configure-playbooks:
        type: string
        required: true
        description: List of playbooks used to configure the hypervisor, separated by space.
      hyp-test-playbooks:
        type: string
        required: true
        description: List of playbooks used to test the hypervisor, separated by space.
      vms-inventories:
        type: string
        required: false
        default: ""
        description: --inventory flags for the VMs, or empty if VMs should not be deployed and tested.
      vms-deploy-playbooks:
        type: string
        required: false
        description: |
          List of playbooks used to deploy the VMs, separated by space.
          Those playbooks are launched with both the hypervisor and VMs inventories.
      vms-configure-playbooks:
        type: string
        required: false
        description: |
          List of playbooks used to configure the VMs, separated by space.
          Those playbooks are launched with the VMs inventories only.
      vms-test-playbooks:
        type: string
        required: false
        description: List of playbooks used to test the VMs, separated by space.
      ansible_ssh_keyfile:
        type: string
        required: false
        description: |
          Path to a private SSH key to use to connect to Ansible hosts.
          Should be a path relative to the Ansible directory.
          e.g. 'inventories_private/ci_rsa'
      compliance_matrices_folder:
        type: string
        required: false
        description: |
          Name of the folder containing the compliance matrices .csv files.
          If empty, no matrices will be created.
          e.g. 'yocto'
      skip_cyclictest:
        type: boolean
        default: false
        description: |
          Don't expect the test playbooks to run Cyclictests. Can be overriden
          per host with the 'skip_cyclictest' Ansible variable.

env:
  # TODO make this better
  INVENTORY_PUBLISHER: "inventories_private/ci_publisher.yaml"
  CYCLICTEST_DURATION: 20
  CYCLICTEST_INTERVAL: 200 # hardcoded in the cyclictest role for now
  LATENCY_MAXIMAL_HYP: 100
  LATENCY_MAXIMAL_VM: 100
  PCAP_LOOP: 10
  PCAP: "/seapath-ci/pcaps/8_streams_4000_SV.pcap"

jobs:
  run-tests:
    name: Run tests
    runs-on: "${{ inputs.runner-label }}"
    defaults:
      run:
        shell: bash
    env:
      RESULTS_FOLDER: ${{ github.workspace }}/test_results
      FAILED: false # can be changed if tests fail
      DO_LATENCY_TESTS: false # automatically changed below
      DO_CYCLIC_TESTS: false
    steps:
      - name: Clean working directory
        if: ${{ always() }}
        run: |
          rm -rf ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}

      - name: Checkout Ansible repository
        uses: actions/checkout@v6
        with:
          path: ansible

      - name: Prepare Ansible
        working-directory: ansible
        run: |
          git clone -q -b ${{ inputs.inventories-repository-branch }} "${{ inputs.inventories-repository }}" inventories_private

          cqfd init
          cqfd -b prepare

          mkdir ${{ env.RESULTS_FOLDER }}
          CQFD_EXTRA_RUN_ARGS="$CQFD_EXTRA_RUN_ARGS -v ${{ env.RESULTS_FOLDER }}:/results"

          if [[ -n "${{ inputs.ansible_ssh_keyfile }}" ]]; then
            chmod 0600 "${{ inputs.ansible_ssh_keyfile }}"
            CQFD_EXTRA_RUN_ARGS="$CQFD_EXTRA_RUN_ARGS -e ANSIBLE_PRIVATE_KEY_FILE=${{ inputs.ansible_ssh_keyfile }}"
          fi

          echo "CQFD_EXTRA_RUN_ARGS=$CQFD_EXTRA_RUN_ARGS" >> "$GITHUB_ENV"

      - name: Configure SEAPATH on hypervisors
        id: configure-hyp
        working-directory: ansible
        run: |
          echo "::group::Hypervisor configuration playbooks"

          cqfd exec ansible-playbook \
            ${{ inputs.hyp-configure-playbooks }} \
            ${{ inputs.hyp-inventories }}

          echo "::endgroup::"

          # Create a JSON object with data about the hypervisors
          hyp=$(cqfd exec ansible-inventory --list \
            ${{ inputs.hyp-inventories }} \
            --limit "standalone_machine,cluster_machines" \
            2> /dev/null \
            | jq -c '._meta.hostvars | map_values({
                skip_cyclictest: (.skip_cyclictest // ${{ inputs.skip_cyclictest }}),
            })'
          )
          hyp_pretty_list=$(echo "$hyp" | jq -r 'keys | join(", ")')
          echo "Running on hypervisors $hyp_pretty_list"
          echo "INVENTORY_HYP=$hyp" >> "$GITHUB_ENV"

      - name: Fetch hypervisors information
        working-directory: ansible
        run: |
          # Those run args allow to have a clean JSON output that can be parsed.
          CQFD_EXTRA_RUN_ARGS="\
            $CQFD_EXTRA_RUN_ARGS \
            -e ANSIBLE_HOST_PATTERN_MISMATCH=ignore \
            -e ANSIBLE_LOAD_CALLBACK_PLUGINS=true \
            -e ANSIBLE_STDOUT_CALLBACK=json \
            -e ANSIBLE_CALLBACKS_ENABLED=null \
          " \
          cqfd exec ansible \
            standalone_machine,cluster_machines \
            ${{ inputs.hyp-inventories }} \
            --module-name setup \
            | jq '.plays[0].tasks[0].hosts | {host_facts: with_entries(.value = .value.ansible_facts)}' \
            > ${{ env.RESULTS_FOLDER}}/hypervisors_facts.json

      - name: Test hypervisors
        id: test-hyp
        working-directory: ansible
        run: |
          echo "::group::Hypervisor test playbooks"

          cqfd exec ansible-playbook \
            ${{ inputs.hyp-test-playbooks }} \
            ${{ inputs.hyp-inventories }} \
            --limit "standalone_machine,cluster_machines" \
            --extra-vars "cukinia_test_prefix=/results" \
            --extra-vars "cyclictest_result_folder=/results" \
            --extra-vars "cyclictest_duration=${{ env.CYCLICTEST_DURATION }}" \

          echo "::endgroup::"

          # Check for kernel backtrace error. This is a random error so it must not
          # stop the CI but just display a warning
          # See https://github.com/seapath/ansible/issues/164
          if grep '<failure' ${{ env.RESULTS_FOLDER }}/*.xml | grep -q '00080'; then
            echo "::warning title=${{ inputs.seapath-flavor }} Hypervisor::kernel back trace detected, see https://github.com/seapath/ansible/issues/164"
          fi

          if grep '<failure' ${{ env.RESULTS_FOLDER }}/*.xml | grep -q -v '00080'; then
            echo "::error title=${{ inputs.seapath-flavor }} Hypervisor::Test fails, see associated test report"
            echo "FAILED=true" >> "$GITHUB_ENV"
          fi

          for hyp in $(echo $INVENTORY_HYP | jq -r 'map_values(select(.skip_cyclictest == false)) | keys | join(" ")'); do
            file="${{ env.RESULTS_FOLDER }}/cyclictest_${hyp}.txt"
            if [[ -f "$file" ]]; then
              max_latency=$(grep "Max Latencies" "$file" | tr " " "\n" | sort -n | tail -1 | sed s/^0*//)
              echo "LATENCY_HYP_${hyp}=${max_latency}" >> "$GITHUB_ENV"
              echo "::notice title=${{ inputs.seapath-flavor }} Hypervisor $hyp::Max latency: $max_latency µs"
              if [[ "$max_latency" -gt "${{ env.LATENCY_MAXIMAL_HYP }}" ]]; then
                echo "::error title=${{ inputs.seapath-flavor }} Hypervisor $hyp::Max latency $max_latency exceeded limit ${{ env.LATENCY_MAXIMAL_HYP }} µs"
                echo "FAILED=true" >> "$GITHUB_ENV"
              fi
            fi
          done

      - name: Deploy SEAPATH VMs
        id: deploy-vms
        working-directory: ansible
        if: "${{ inputs.vms-inventories != '' }}"
        run: |
          echo "::group::VM deployment playbooks"

          CQFD_EXTRA_RUN_ARGS="\
            $CQFD_EXTRA_RUN_ARGS \
            -v /etc/seapath-ci/vm_file:$(pwd)/vm_images \
          " \
          cqfd exec ansible-playbook \
            ${{ inputs.vms-deploy-playbooks }} \
            ${{ inputs.hyp-inventories }} \
            ${{ inputs.vms-inventories }}

          echo "::endgroup::"


          if [[ -n "${{ inputs.vms-configure-playbooks }}" ]]; then
            echo "::group::VM configuration playbooks"

            cqfd exec ansible-playbook \
              ${{ inputs.vms-configure-playbooks }} \
              ${{ inputs.vms-inventories }}

            echo "::endgroup::"
          fi


          # Create a JSON object with data about the VMs
          vms=$(cqfd exec ansible-inventory --list \
            ${{ inputs.vms-inventories }} \
            --limit "VMs" \
            2> /dev/null \
            | jq -c '. as $root | ._meta.hostvars | with_entries(.value = {
                rt: (.value.vm_features // []) | contains(["rt"]),
                skip_cyclictest: (.value.skip_cyclictest // ${{ inputs.skip_cyclictest }}),
                sv_subscriber: (.key as $key | ($root.subscriber.hosts // []) | any(select(. == $key))), # works only if members of group subscriber are not transitive
            })'
          )

          vms_pretty_list=$(echo "$vms" | jq -r 'to_entries | map(if .value.rt then .key + " (RT)" else .key end) | join(", ")')
          echo "Deployed VMs $vms_pretty_list"
          echo "INVENTORY_VMS=$vms" >> "$GITHUB_ENV"

          echo "DO_LATENCY_TESTS=$(echo "$vms" | jq 'any(.[]; .sv_subscriber == true and .rt == true)')" >> "$GITHUB_ENV"

      # TODO weekly benchmark

      - name: Test VMs
        id: test-vms
        if: "${{ steps.deploy-vms.outcome == 'success' }}"
        working-directory: ansible
        run: |
          echo "::group::VM test playbooks"

          cqfd exec ansible-playbook \
            ${{ inputs.vms-test-playbooks }} \
            ${{ inputs.vms-inventories }} \
            --limit "VMs" \
            --extra-vars "cukinia_test_prefix=/results" \
            --extra-vars "cyclictest_result_folder=/results" \
            --extra-vars "cyclictest_duration=${{ env.CYCLICTEST_DURATION }}" \

          echo "::endgroup::"

          for vm in $(echo $INVENTORY_VMS | jq -r 'keys | join(" ")'); do
            if grep '<failure' ${{ env.RESULTS_FOLDER }}/cukinia_${vm}.xml | grep -q -v '00080'; then
              echo "::error title=${{ inputs.seapath-flavor }} VMs::Test fails for ${vm}, see associated test report"
              echo "FAILED=true" >> "$GITHUB_ENV"
            fi
          done

          for vm in $(echo $INVENTORY_VMS | jq -r 'map_values(select(.skip_cyclictest == false and .rt == true)) | keys | join(" ")'); do
            file="${{ env.RESULTS_FOLDER }}/cyclictest_${vm}.txt"
            if [[ -f "$file" ]]; then
              max_latency=$(grep "Max Latencies" "$file" | tr " " "\n" | sort -n | tail -1 | sed s/^0*//)
              echo "LATENCY_VM_${vm}=${max_latency}" >> "$GITHUB_ENV"
              echo "::notice title=${{ inputs.seapath-flavor }} VM $vm::Max latency: $max_latency µs"
              if [[ "$max_latency" -gt "${{ env.LATENCY_MAXIMAL_VM }}" ]]; then
                echo "::error title=${{ inputs.seapath-flavor }} VM $vm::Max latency $max_latency exceeded limit ${{ env.LATENCY_MAXIMAL_VM }} µs"
                echo "FAILED=true" >> "$GITHUB_ENV"
              fi
            fi
          done

      - name: Checkout svtrace-ansible repository
        uses: actions/checkout@v6
        if: "${{ steps.deploy-vms.outcome == 'success' && env.DO_LATENCY_TESTS == 'true' }}"
        with:
          repository: seapath/svtrace-ansible
          path: svtrace-ansible

      - name: Do latency tests on VMs
        working-directory: svtrace-ansible
        if: "${{ steps.deploy-vms.outcome == 'success' && env.DO_LATENCY_TESTS == 'true' }}"
        run: |
          git clone -q -b ${{ inputs.inventories-repository-branch }} "${{ inputs.inventories-repository }}" inventories_private

          echo "::group::Initialize svtrace-ansible"
          cqfd init
          echo "::endgroup::"

          export CQFD_EXTRA_RUN_ARGS=" \
            $CQFD_EXTRA_RUN_ARGS \
            -v /var/run/docker.sock:/var/run/docker.sock \
          "

          echo "::group::Configure latency tests"

          cqfd exec ansible-playbook \
            playbooks/configure_latency_tests.yaml \
            --limit "localhost,sv_publisher,VMs" \
            --inventory ${{ env.INVENTORY_PUBLISHER }} \
            ${{ inputs.vms-inventories }} \

          echo "::endgroup::"
          echo "::group::Run latency tests"

          cqfd exec ansible-playbook \
            playbooks/run_latency_tests.yaml \
            --limit "localhost,sv_publisher,VMs" \
            --inventory ${{ env.INVENTORY_PUBLISHER }} \
            ${{ inputs.vms-inventories }} \
            --extra-vars "pcap=${{ env.PCAP }}" \
            --extra-vars "pcap_cycles=${{ env.PCAP_LOOP }}" \
            --extra-vars "stream_to_log=0000"

          echo "::endgroup::"

          for vm in $(echo $INVENTORY_VMS | jq -r 'map_values(select(.sv_subscriber == true and .rt == true)) | keys | join(" ")'); do
            latency_test_dir=tests_results/data/ci_latency_tests_${vm}

            if [[ ! -d "$latency_test_dir" ]]; then
              echo "::error::Test results not found for VM $vm"
              exit 1
            fi

            cp ${latency_test_dir}/results/*.png "${{ env.RESULTS_FOLDER }}"
            cp "${latency_test_dir}/results/latency_tests.adoc" "${{ env.RESULTS_FOLDER }}/latency_tests_${vm}.adoc"

            if grep -q "FAILED" "${latency_test_dir}/results/latency_tests.adoc"; then
              echo "::error title=${{ inputs.seapath-flavor }} VM $vm::Latency test failed, see associated test report"
              echo "FAILED=true" >> "$GITHUB_ENV"
            fi
          done

      - name: Upload raw results # used for debugging
        id: raw-results-artifact
        uses: actions/upload-artifact@v7
        with:
          name: raw-results-${{ inputs.seapath-flavor }}
          path: ${{ env.RESULTS_FOLDER }}
          include-hidden-files: true
          retention-days: 1
          if-no-files-found: error

      - name: Checkout test-report-pdf
        uses: actions/checkout@v6
        with:
          repository: savoirfairelinux/test-report-pdf
          path: test-report-pdf

      - name: Prepare report generation
        working-directory: test-report-pdf
        run: |
          cqfd init

          mkdir include
          cp -r ${{ env.RESULTS_FOLDER }}/* include/
          cp ../ansible/.github/test-report/prerequisites.adoc include/

          latency_tests_duration=$(python3 -c "import datetime; print(datetime.timedelta(seconds=${{ env.PCAP_LOOP }}))")
          echo "LATENCY_TESTS_DURATION=$latency_tests_duration" >> "$GITHUB_ENV"

          echo "$INVENTORY_HYP" "$INVENTORY_VMS" | jq --slurp '{hypervisors: .[0], vms: .[1]}' > ${{ env.RESULTS_FOLDER }}/data.json

          echo "DO_CYCLIC_TESTS=$(jq \
            'any(.vms[]; .skip_cyclictest == false and .rt == true)
            or any(.hypervisors[]; .skip_cyclictest == false)'\
            ${{ env.RESULTS_FOLDER }}/data.json
          )" >> "$GITHUB_ENV"

      - name: Generate Cyclictest plots
        if: "${{ env.DO_CYCLIC_TESTS == 'true' }}"
        working-directory: test-report-pdf
        run: |
          for hyp in $(echo $INVENTORY_HYP | jq -r 'map_values(select(.skip_cyclictest == false)) | keys | join(" ")'); do
            echo "Generating Cyclictest plot for $hyp"

            ../ansible/.github/test-report/cyclictest_plot.sh \
              -i "${{ env.RESULTS_FOLDER }}/cyclictest_${hyp}.txt" \
              -o "include/cyclictest_${hyp}.png" \
              -l "${{ env.LATENCY_MAXIMAL_HYP }}"
          done

          for vm in $(echo $INVENTORY_VMS | jq -r 'map_values(select(.skip_cyclictest == false and .rt == true)) | keys | join(" ")'); do
            echo "Generating Cyclictest plot for $vm"

            ../ansible/.github/test-report/cyclictest_plot.sh \
              -i "${{ env.RESULTS_FOLDER }}/cyclictest_${vm}.txt" \
              -o "include/cyclictest_${vm}.png" \
              -l "${{ env.LATENCY_MAXIMAL_VM }}"
          done

      - name: Templatize system information
        uses: cuchi/jinja2-action@8bd801365a8d36a0b20f45ee969161685de7785a # v1.3.0
        with:
          template: ansible/.github/test-report/system_info.adoc.j2
          output_file: test-report-pdf/include/system_info.adoc
          strict: true
          data_file: "${{ env.RESULTS_FOLDER }}/hypervisors_facts.json"

      - name: Templatize notes
        uses: cuchi/jinja2-action@8bd801365a8d36a0b20f45ee969161685de7785a # v1.3.0
        with:
          template: ansible/.github/test-report/notes.adoc.j2
          output_file: test-report-pdf/include/notes.adoc
          strict: true
          data_file: "${{ env.RESULTS_FOLDER }}/data.json"
          # uses env variables to populate the document

      - name: Templatize cyclictest results
        uses: cuchi/jinja2-action@8bd801365a8d36a0b20f45ee969161685de7785a # v1.3.0
        if: "${{ env.DO_CYCLIC_TESTS == 'true' }}"
        with:
          template: ansible/.github/test-report/cyclictest.adoc.j2
          output_file: test-report-pdf/include/cyclictest.adoc
          strict: true
          data_file: "${{ env.RESULTS_FOLDER }}/data.json"
          # uses env variables to populate the document

      - name: Templatize latency tests results
        uses: cuchi/jinja2-action@8bd801365a8d36a0b20f45ee969161685de7785a # v1.3.0
        if: "${{ env.DO_LATENCY_TESTS == 'true' }}"
        with:
          template: ansible/.github/test-report/latency_tests.adoc.j2
          output_file: test-report-pdf/include/latency_tests.adoc
          strict: true
          data_file: "${{ env.RESULTS_FOLDER }}/data.json"
          # uses env variables to populate the document

      - name: Generate test report
        working-directory: test-report-pdf
        run: |
          compliance_matrices=()
          if [[ -n "${{ inputs.compliance_matrices_folder }}" ]]; then
            for matrix in ../ansible/.github/test-report/bp28-compliance-matrices/${{ inputs.compliance_matrices_folder }}/*; do
              matrix_name="$(basename $matrix)"
              echo "Found compliance matrix $matrix_name"
              compliance_matrices+=(--compliance_matrix "/report/bp28-compliance-matrices/${{ inputs.compliance_matrices_folder }}/$matrix_name")
            done
          fi

          CQFD_EXTRA_RUN_ARGS="-v $(realpath ../ansible/.github/test-report):/report" \
          cqfd exec ./compile.py \
            --contact_email "seapath@savoirfairelinux.com" \
            --client_name "SEAPATH" \
            --project_name "SEAPATH" \
            --subtitle "${{ inputs.seapath-flavor }}" \
            --add_machine_name \
            --pdf_themes_dir "/report/seapath-themes" \
            --include_dir "./include" \
            ${compliance_matrices[@]} \
            --allow_absent \
            --merge_compliance_matrices \
            --show_failed_cdata

          mv test-report.pdf "SEAPATH ${{ inputs.seapath-flavor }} Tests Report.pdf"

      - name: Upload test report
        uses: actions/upload-artifact@v7
        with:
          path: test-report-pdf/*.pdf
          if-no-files-found: error
          archive: false

      # When the workflow detects a failing test, it does not stop the workflow
      # directly. Thus, we fail this workflow at the end if one failing test
      # has been previously detected.
      - name: Fail if needed
        if: "${{ env.FAILED == 'true' }}"
        run: |
          exit 1
