# Copyright (C) 2025, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

name: CI Debian

on:
  workflow_call:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  call-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Standalone
            hyp-inventories: >-
              --inventory inventories_private/standalone13.yml
            vms-inventories: >-
              --inventory inventories_private/vm13standalone.yml
            vms-deployment-playbooks: >-
              playbooks/deploy_vms_standalone.yaml
          - name: Cluster
            hyp-inventories: >-
              --inventory inventories_private/cluster13.yml
            vms-inventories: >-
              --inventory inventories_private/vm13cluster.yml
            vms-deployment-playbooks: >-
              playbooks/deploy_vms_cluster.yaml
    uses: ./.github/workflows/_tests.yml
    name: Run tests on ${{ matrix.name }}
    with:
      seapath-flavor: "Debian ${{ matrix.name }}"
      compliance_matrices_folder: debian
      runner-label: "runner-RTE-13"
      inventories-repository: "git@github.com:insatomcat/seapath_inventories_ci.git"
      ansible_ssh_keyfile: "inventories_private/ci_rsa"
      skip_cyclictest: true # the inventories don't have the expected skip_cyclictest variables
      hyp-inventories: ${{ matrix.hyp-inventories }}
      hyp-configure-playbooks: >-
        playbooks/ci_configure.yaml
      hyp-test-playbooks: >-
        playbooks/ci_test.yaml
      vms-inventories: ${{ matrix.vms-inventories }}
      vms-deploy-playbooks: ${{ matrix.vms-deployment-playbooks }}
      vms-configure-playbooks: >-
        playbooks/seapath_setup_prerequisitesdebian.yaml
        playbooks/seapath_setup_hardening.yaml
        playbooks/ci_prepare_VMs.yaml
      vms-test-playbooks: >-
        playbooks/ci_test.yaml
