# Copyright (C) 2025, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

name: Molecule

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  molecule-role:
    name: Molecule Role Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Install Python dependencies
        run: pip install -r molecule_requirements.txt

      - name: Run Molecule Roles tests
        run: bash scripts/run-molecule-roles.sh

  molecule-playbooks:
    name: Molecule Playbook Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Install Python dependencies
        run: pip install -r molecule_requirements.txt

      - name: Run Molecule Playbook tests
        working-directory: playbooks
        run: molecule test --all
