# Copyright (C) 2023, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

name: CI OracleLinux

on:
  workflow_call:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  call-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Cluster
            runner-label: runner-RTE-OL9-cluster
            hyp-inventories: >-
              --inventory inventories_private/clusterol9.yml
            vms-inventories: >-
              --inventory inventories_private/vmol9cluster.yml
            vms-deployment-playbooks: >-
              playbooks/deploy_vms_cluster.yaml
          - name: Standalone
            runner-label: runner-RTE-OL9-standalone
            hyp-inventories: >-
              --inventory inventories_private/standaloneol9.yml
            vms-inventories: >-
              --inventory inventories_private/vmol9standalone.yml
            vms-deployment-playbooks: >-
              playbooks/deploy_vms_standalone.yaml
    uses: ./.github/workflows/_tests.yml
    name: Run tests on ${{ matrix.name }}
    with:
      seapath-flavor: "OracleLinux ${{ matrix.name }}"
      runner-label: ${{ matrix.runner-label }}
      inventories-repository: "git@github.com:insatomcat/seapath_inventories_ci.git"
      ansible_ssh_keyfile: "inventories_private/ci_rsa"
      skip_cyclictest: true # ci_test.yaml does not run cyclictests
      hyp-inventories: ${{ matrix.hyp-inventories }}
      hyp-configure-playbooks: >-
        playbooks/ci_configure.yaml
      hyp-test-playbooks: >-
        playbooks/ci_test.yaml
      vms-inventories: ${{ matrix.vms-inventories }}
      vms-deploy-playbooks: ${{ matrix.vms-deployment-playbooks }}
      vms-configure-playbooks: >-
        playbooks/seapath_setup_prerequisitesdebian.yaml
        playbooks/seapath_setup_hardening.yaml
        playbooks/ci_prepare_VMs.yaml
      vms-test-playbooks: >-
        playbooks/ci_test.yaml
