# Copyright (C) 2025, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

name: QA

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install dependencies
        run: |
          pip install ansible-core~=2.16.0 ansible-lint
          ansible-galaxy collection install -r ansible-requirements.yaml

      - name: Setup Ansible environment
        run: |
          sudo mkdir -p /etc/ansible/hosts /etc/ansible/roles
          sudo cp inventories/examples/seapath-cluster.yaml /etc/ansible/hosts/hosts.yaml
          sudo cp -r ceph-ansible/roles/* /etc/ansible/roles/
          cp src/ceph-ansible-site.yaml ceph-ansible/site.yml

      - name: Run ansible-lint
        run: ansible-lint -c ansible-lint.conf
