# Copyright (C) 2023-2024 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

name: CI Yocto

env:
  WORK_DIR: /tmp/seapath_ci_${{ github.run_id }}_${{ github.run_attempt }}_${{ github.sha }}
on:
  workflow_call:
    inputs:
      pcap_loop:
        default: 60
        required: false
        type: number
      weekly:
        default: false
        required: false
        type: boolean
  workflow_dispatch:

permissions:
  checks: write

jobs:
  call-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Welotec RSAPC Mk2
            hyp-inventories: >-
              --inventory inventories_private/ci_yocto_standalone.yaml
            vms-inventories: >-
              --inventory inventories_private/ci_vms.yaml
          - name: Aaeon ARM I.MX8P-2G
            hyp-inventories: >-
              --inventory inventories_private/ci_yocto_standalone_aaeon.yaml
    uses: ./.github/workflows/_tests.yml
    name: Run tests on ${{ matrix.name }}
    with:
      seapath-flavor: "Yocto ${{ matrix.name }}"
      compliance_matrices_folder: yocto
      runner-label: "runner-SFL"
      inventories-repository: "git@github.com:seapath-ci/ci-seapath-yocto-inventories.git"
      hyp-inventories: ${{ matrix.hyp-inventories }}
      hyp-configure-playbooks: >-
        playbooks/ci_standalone_setup.yaml
        playbooks/ci_prepare_publisher.yaml
      hyp-test-playbooks: >-
        playbooks/ci_all_machines_tests.yaml
      vms-inventories: ${{ matrix.vms-inventories }}
      vms-deploy-playbooks: >-
        playbooks/ci_vms_standalone_ptp.yaml
      vms-test-playbooks: >-
        playbooks/ci_all_machines_tests.yaml
