# Copyright (C) 2024 RTE
# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure SHUTDOWN_TIMEOUT is set to 20 # for Standalone
  ansible.builtin.lineinfile:
    path: /etc/default/libvirt-guests
    regexp: "^#?SHUTDOWN_TIMEOUT=.*"
    line: "SHUTDOWN_TIMEOUT=20"
